version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "80:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
  
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_etc:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=changeMe
      - DOCKER_INFLUXDB_INIT_ORG=eau-to-matik
      - DOCKER_INFLUXDB_INIT_BUCKET=eau-to-matik
      - DOCKER_INFLUXDB_INIT_MODE=setup
      # TODO: specify a token
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

volumes:
  grafana_data:
  influxdb_data:
  influxdb_etc: