version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "80:3000"
    volumes:
      - data:/var/lib/grafana
    restart: unless-stopped

volumes:
  data: